modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1 = FML 47.x
license="MIT"

[[mods]]
modId="arl"
version="1.0.0"
displayName="ARL"
description='''
Action Roguelike MOD for Minecraft Forge 1.20.1
'''

# Optional
authors="Risudayooo"
displayURL="https://github.com/Risudayooo/ARL"